#!/usr/bin/env python3

import argparse, socket, time, json, select, struct, math, copy, functools as ft

#DEBUG = True
DEBUG = False

parser = argparse.ArgumentParser(description='route packets')
parser.add_argument('asn', type=int, help="AS Number")
parser.add_argument('networks', metavar='networks', type=str, nargs='+', help="networks")
args = parser.parse_args()

##########################################################################################

# Message Fields
TYPE = "type"
SRCE = "src"
DEST = "dst"
MESG = "msg"
TABL = "table"

# Message Types
DATA = "data"
DUMP = "dump"
UPDT = "update"
RVKE = "revoke"
NRTE = "no route"

# Update Message Fields
NTWK = "network"
NMSK = "netmask"
ORIG = "origin"
LPRF = "localpref"
APTH = "ASPath"
SORG = "selfOrigin"

# internal route info
CUST = "cust"
PEER = "peer"
PROV = "prov"


##########################################################################################
""" Route class which holds information about a route on the network."""
class Route: 
    port = None
    network = None
    netMask = None
    localPref = None
    selfOrigin = None
    ASPath = None
    origin = None
    def __init__(self, port, packet):
        self.port = port
        self.network = packet[MESG][NTWK]
        self.netmask = packet[MESG][NMSK]
        self.localPref = packet[MESG][LPRF]
        self.selfOrigin = packet[MESG][SORG]
        self.ASPath = packet[MESG][APTH]
        self.origin = packet[MESG][ORIG]

""" Performs a bitwise and operation on two IP addresses. The addresses are strings formatted as 111.222.333.444"""
def and_ip_strings(ip1, ip2):
    ip1_split = ip1.split(".")
    ip2_split = ip2.split(".")
    result = []
    for i in range(len(ip1_split)):
       result.append(str(int(ip1_split[i]) & int(ip2_split[i]))) 
    return ft.reduce(lambda x, y: x + "." + y, result)

class Router:
    asn = None
    routes = None
    updates = None
    relations = None
    sockets = None

    def __init__(self, asn, networks):
        self.asn = asn
        self.routes = {} # {port: Route[]}
        self.updates = []
        self.relations = {}
        self.sockets = {}
        for relationship in networks:
            network, relation = relationship.split("-")
            if DEBUG: 
                print("Starting socket for", network, relation)
            self.sockets[network] = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
            self.sockets[network].setblocking(0)
            self.sockets[network].connect(network)
            self.relations[network] = relation
            self.routes[network] = []
        return

    def lookup_routes(self, daddr):
        """ Lookup all valid routes for an address """
        outroutes = []
        for port in self.routes.keys():
            for route in self.routes[port]:
                translated_daddr = and_ip_strings(daddr, route.netmask)
                if translated_daddr == route.network:
                    outroutes.append(route)
        return outroutes

    def get_shortest_as_path(self, routes):
        """ select the route with the shortest AS Path """
        if len(routes) == 0:
            return []
        shortest_routes = [routes[0]]
        shortest_length = routes[0].ASPath.count(",") + 1
        for route_index in range(1, len(routes)):
            current_route = routes[route_index]
            current_length = current_route.ASPath.count(",") + 1
            if current_length == shortest_length:
                shortest_routes.append(current_route)
            elif current_length < shortest_length:
                shortest_length = current_length
                shortest_routes = [current_route]
        return shortest_routes
            
    def get_highest_preference(self, routes):
        """ select the route with the highest local pref """
        if len(routes) == 0:
            return []
        highest_routes = [routes[0]]
        highest_pref = routes[0].localPref
        for route_index in range(1, len(routes)):
            current_route = routes[route_index]
            if current_route.localPref == highest_pref:
                highest_routes.append(current_route)
            elif current_route.localPref > highest_pref:
                highest_pref = current_route.localPref
                highest_routes = [current_route]
        return highest_routes
         
    def get_self_origin(self, routes):
        """ select self originating routes """
        outroutes = []
        for route in routes:
            if DEBUG:
              print(route.selfOrigin)
            if route.selfOrigin:
                outroutes.append(route)
        return outroutes

    def get_origin_routes(self, routes):
        """ select origin routes: IGP > EGP > UNK """
        outroutes = []
        current_priority = "UNK"
        better = ["EGP", "IGP"]
        for route in routes:
            if route.origin == current_priority:
                outroutes.append(routes)
            elif route.origin in better:
                current_priority = route.origin
                better.remove(route.origin)
                outroutes = [route]

        return outroutes
        

    def filter_relationships(self, srcif, routes):
        """ Don't allow Peer->Peer, Peer->Prov, or Prov->Peer forwards """
        outroutes = []
        for route in routes:
            srcif_rel = self.relations[srcif]
            route_rel = self.relations[route.port]
            if (srcif_rel == CUST or route_rel == CUST):
                outroutes.append(route)
            elif (srcif_rel == PROV and route_rel == PROV):
                outroutes.append(route)
        return outroutes

    def get_route(self, srcif, daddr):
        """	Select the best route for a given address	"""
        routes = self.lookup_routes(daddr)
        # Rules go here
        if routes:
            # 1. Highest Preference
            routes = self.get_highest_preference(routes)
            # 2. Self Origin
            routes = self.get_self_origin(routes)
            # 3. Shortest ASPath
            routes = self.get_shortest_as_path(routes)
            # 4. IGP > EGP > UNK
            routes = self.get_origin_routes(routes)
            # 5. Lowest IP Address
            # TODO
            # Final check: enforce peering relationships
            routes = self.filter_relationships(srcif, routes)
        # TODO: may need to use submask for line below instead of returning first index
        return routes[0] if len(routes) > 0 else None
    def forward(self, srcif, packet):
        """	Forward a data packet	"""
        if DEBUG:
          print("routes are")
        route = self.get_route(srcif, packet[DEST])
        self.sockets[route.port].sendall(bytearray(json.dumps(packet).encode()))
	
        

    def coalesce(self):
        """	coalesce any routes that are right next to each other	"""
        # TODO (this is the most difficult task, save until last)
        return False

    def update(self, srcif, packet):
        """	handle update packets	"""
        self.routes[srcif].append(Route(srcif, packet))
        packet_copy = copy.deepcopy(packet)
        packet_copy[MESG][APTH].append(self.asn)
        if self.relations[srcif] == CUST:
            for socket in self.sockets.keys():
                if socket != srcif:
                    packet_copy[SRCE] = socket[:len(socket)-1] + "1"
                    packet_copy[DEST] = socket
                    packet_json = json.dumps(packet_copy)
                    packet_json_encoded_bytes = bytearray(packet_json.encode())
                    self.sockets[socket].sendall(packet_json_encoded_bytes)
        else:
           for socket in self.sockets.keys():
                if socket != srcif and not(self.relations[socket] in [PROV, PEER]):
                    packet_copy[SRCE] = socket[:len(socket)-1] + "1"
                    packet_copy[DEST] = socket
                    packet_json = json.dumps(packet_copy)
                    packet_json_encoded_bytes = bytearray(packet_json.encode())
                    self.sockets[socket].sendall(packet_json_encoded_bytes) 
    
    def revoke(self, packet):
        """	handle revoke packets	"""
        # TODO
        return True

    def dump(self, packet):
        """	handles dump table requests	"""
        packet_copy = copy.deepcopy(packet)
        packet_copy[SRCE] = packet[DEST]
        packet_copy[DEST] = packet[SRCE]
        packet_copy[TYPE] = TABL
        table = []
        for port in self.routes.keys():
            for routes in self.routes[port]:
                table.append({"network": routes.network, "netmask":routes.netmask, "peer": port})
        packet_copy[MESG] = table
        self.sockets[packet_copy[DEST]].sendall(bytearray(json.dumps(packet_copy).encode()))
        
        return True

    def handle_packet(self, srcif, packet):
        """	dispatches a packet """
        # TODO
        if packet["type"] == UPDT:
            self.update(srcif, packet)
        elif packet["type"] == DUMP:
            self.dump(packet)
        elif packet["type"] == DATA:
            self.forward(srcif, packet)
        else:
            return

    def send_error(self, conn, msg):
        """ Send a no_route error message """
        # TODO
        return

    def run(self):
        while True:
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]
            for conn in socks:
                try:
                    k = conn.recv(65535)
                except:
                    # either died on a connection reset, or was SIGTERM's by parent
                    return
                if k:
                    for sock in self.sockets:
                        if self.sockets[sock] == conn:
                            srcif = sock
                    msg = json.loads(k)
                    if DEBUG:
                      print(msg)
                    if not self.handle_packet(srcif, msg):
                        self.send_error(conn, msg)
                else:
                    return
        return

if __name__ == "__main__":
    router = Router(args.asn ,args.networks)
    router.run()
